global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: 'bank-management'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:8090' ]
        labels:
          application: 'Bank Management Application'